¡Hola, Iris!

Mi nombre es Tonatiuh Cruz. Me complace revisar tu proyecto hoy.

Al identificar cualquier error inicialmente, simplemente los destacaré. Te animo a localizar y abordar los problemas de forma independiente como parte de tu preparación para un rol como data-scientist. En un entorno profesional, tu líder de equipo seguiría un emnfoque similar. Si encuentras la tarea desafiante, proporcionaré una pista más específica en la próxima iteración.

Encontrarás mis comentarios a continuación - **por favor no los muevas, modifiques o elimines**.

Puedes encontrar mis comentarios en cajas verdes, amarillas o rojas como esta:

<div class="alert alert-block alert-success">
<b>Comentario del revisor</b> <a class="tocSkip"></a>

Éxito. Todo está hecho correctamente.
</div>

<div class="alert alert-block alert-warning">
<b>Comentario del revisor</b> <a class="tocSkip"></a>

Observaciones. Algunas recomendaciones.
</div>

<div class="alert alert-block alert-danger">
<b>Comentario del revisor</b> <a class="tocSkip"></a>

Necesita corrección. El bloque requiere algunas correcciones. El trabajo no puede ser aceptado con comentarios en rojo.
</div>

Puedes responderme utilizando esto:

<div class="alert alert-block alert-info">

Proyecto SQL

In [13]:
import pandas as pd
from sqlalchemy import create_engine

db_config = {'user': 'practicum_student',
             'pwd': 's65BlTKV3faNIGhmvJVzOqhs',
             'host': 'rc1b-wcoijxj3yxfsf3fs.mdb.yandexcloud.net',
             'port': 6432,
             'db': 'data-analyst-final-project-db'}

connection_string = 'postgresql://{}:{}@{}:{}/{}'.format(
    db_config['user'],
    db_config['pwd'],
    db_config['host'],
    db_config['port'],
    db_config['db']
)

engine = create_engine(connection_string, connect_args={'sslmode': 'require'})

In [14]:
tables = ['books', 'authors', 'publishers', 'ratings', 'reviews']

for table in tables:
    print(f"\nTabla: {table}")
    display(pd.read_sql(f"SELECT * FROM {table} LIMIT 5;", engine))

Tabla: books

,book_id,author_id,title,num_pages,publication_date,publisher_id
0,1,546,'Salem's Lot,594,2005-11-01,93
1,2,465,1 000 Places to See Before You Die,992,2003-05-22,336
2,3,407,13 Little Blue Envelopes (Little Blue Envelope...,322,2010-12-21,135
3,4,82,1491: New Revelations of the Americas Before C...,541,2006-10-10,309
4,5,125,1776,386,2006-07-04,268

Tabla: authors

   author_id                          author
0          1                      A.S. Byatt
1          2  Aesop/Laura Harris/Laura Gibbs
2          3                 Agatha Christie
3          4                   Alan Brennert
4          5        Alan Moore/David   Lloyd

Tabla: publishers

   publisher_id                          publisher
0             1                                Ace
1             2                           Ace Book
2             3                          Ace Books
3             4                      Ace Hardcover
4             5  Addison Wesley Publishing Company

Tabla: ratings

   rating_id  book_id       username  rating
0          1        1     ryanfranco       4
1          2        1  grantpatricia       2
2          3        1   brandtandrea       5
3          4        2       lorichen       3
4          5        2    mariokeller       2

Tabla: reviews

,review_id,book_id,username,text
0,1,1,brandtandrea,Mention society tell send professor analysis. ...
1,2,1,ryanfranco,Foot glass pretty audience hit themselves. Amo...
2,3,2,lorichen,Listen treat keep worry. Miss husband tax but ...
3,4,3,johnsonamanda,Finally month interesting blue could nature cu...
4,5,3,scotttamara,Nation purpose heavy give wait song will. List...

In [15]:
query_1 = """
SELECT COUNT(*) AS books_after_2000
FROM books
WHERE publication_date > '2000-01-01';
"""

result_1 = pd.read_sql(query_1, engine)
result_1

   books_after_2000
0               819

In [16]:
query_2 = """
SELECT 
    b.book_id,
    b.title,
    COUNT(DISTINCT r.review_id) AS num_reviews,
    AVG(rt.rating) AS avg_rating
FROM books b
LEFT JOIN reviews r ON b.book_id = r.book_id
LEFT JOIN ratings rt ON b.book_id = rt.book_id
GROUP BY b.book_id, b.title
ORDER BY num_reviews DESC;
"""

result_2 = pd.read_sql(query_2, engine)
result_2

,book_id,title,num_reviews,avg_rating
0,948,Twilight (Twilight #1),7,3.662500
1,963,Water for Elephants,6,3.977273
2,734,The Glass Castle,6,4.206897
3,302,Harry Potter and the Prisoner of Azkaban (Harr...,6,4.414634
4,695,The Curious Incident of the Dog in the Night-Time,6,4.081081
...,...,...,...,...
995,83,Anne Rice's The Vampire Lestat: A Graphic Novel,0,3.666667
996,808,The Natural Way to Draw,0,3.000000
997,672,The Cat in the Hat and Other Dr. Seuss Favorites,0,5.000000
998,221,Essential Tales and Poems,0,4.000000
999,191,Disney's Beauty and the Beast (A Little Golden...,0,4.000000

In [17]:
query_3 = """
SELECT 
    p.publisher,
    COUNT(b.book_id) AS num_books
FROM books b
JOIN publishers p ON b.publisher_id = p.publisher_id
WHERE b.num_pages > 50
GROUP BY p.publisher
ORDER BY num_books DESC
LIMIT 1;
"""

result_3 = pd.read_sql(query_3, engine)
result_3

       publisher  num_books
0  Penguin Books         42

In [18]:
query_4 = """
SELECT 
    a.author,
    AVG(rt.rating) AS avg_rating
FROM books b
JOIN authors a ON b.author_id = a.author_id
JOIN ratings rt ON b.book_id = rt.book_id
GROUP BY a.author, b.book_id
HAVING COUNT(rt.rating) >= 50
ORDER BY avg_rating DESC
LIMIT 1;
"""

result_4 = pd.read_sql(query_4, engine)
result_4

                       author  avg_rating
0  J.K. Rowling/Mary GrandPré    4.414634

In [19]:
query_5 = """
WITH active_users AS (
    SELECT username
    FROM ratings
    GROUP BY username
    HAVING COUNT(book_id) > 50
)
SELECT 
    AVG(review_count) AS avg_reviews
FROM (
    SELECT 
        r.username,
        COUNT(rv.review_id) AS review_count
    FROM active_users r
    LEFT JOIN reviews rv ON r.username = rv.username
    GROUP BY r.username
) sub;
"""

result_5 = pd.read_sql(query_5, engine)
result_5

   avg_reviews
0    24.333333

<div class="alert alert-block alert-danger">
<b>Paso 2</b> <a class="tocSkip"></a><br>

Hola, Iris. Como puedes notar no estamos obteniendo resultados esto no se debe a que las consultas están equivocadas. Más bien es a la forma en que cargamos y llamamos a la base genera. Para esto verifica que inicialmente tienes acceso a la base de datos.


<div class="alert alert-block alert-success">
<b>Comentario del revisor</b> <a class="tocSkip"></a>

Gran trabajo con el ajuste!

El objetivo es analizar el comportamiento de los lectores utilizando datos de libros, autores, editoriales, calificaciones y reseñas, para identificar patrones relevantes que ayuden a construir una propuesta de valor para una nueva aplicación de lectura.

C
Libros después del 2000
La base muestra cuántos libros modernos existen, lo que ayuda a entender la relevancia del catálogo actual.

Reseñas y calificaciones
Los libros con más reseñas suelen tener mayor interacción de usuarios, lo que indica popularidad o impacto.

Editorial más productiva
Identifica qué editorial domina el mercado en libros completos (>50 páginas), lo que puede indicar mayor presencia comercial.

Autor mejor calificado
Permite detectar autores con alta calidad percibida por lectores, útiles para recomendaciones o promoción.

Usuarios activos
Los usuarios que califican muchos libros también tienden a generar reseñas, mostrando alto nivel de compromiso con la plataforma.

En este proyecto se utilizaron funciones SQL agregadas como COUNT, AVG y ROUND,
así como cláusulas GROUP BY y HAVING para realizar los cálculos directamente en
la base de datos. La librería pandas se utilizó únicamente para ejecutar las
consultas SQL y mostrar los resultados.

En este proyecto se realizó un análisis de una base de datos relacional que contiene información sobre libros, autores, editoriales, calificaciones y reseñas de usuarios, con el objetivo de obtener insights relevantes para la creación de una propuesta de valor para un nuevo producto orientado a lectores.

A través del uso exclusivo de consultas SQL, se analizaron libros publicados a partir del año 2000, lo que permitió centrar el estudio en contenido relativamente reciente. Asimismo, se evaluó la interacción de los usuarios mediante el número de reseñas y la calificación promedio por libro, identificando títulos con mayor nivel de participación.

El análisis de las editoriales mostró cuál de ellas ha publicado el mayor número de libros con más de 50 páginas, excluyendo publicaciones de poca extensión y permitiendo enfocar el estudio en contenido de mayor valor editorial. De igual forma, se identificó al autor con la calificación promedio más alta considerando únicamente libros con un número significativo de evaluaciones, lo que aporta resultados más confiables y representativos.

Finalmente, se analizó el comportamiento de los usuarios más activos, observando que aquellos que califican un mayor número de libros también tienden a dejar más reseñas de texto, lo que evidencia un alto nivel de compromiso con la plataforma.

En conjunto, los resultados obtenidos permiten comprender mejor tanto la oferta de contenido como el comportamiento de los usuarios, proporcionando una base sólida para la toma de decisiones estratégicas y el desarrollo de nuevos productos dentro del mercado de aplicaciones para amantes de la lectura.